/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Conexao.ConexaoMySQL;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.Timer;

public class Carregar extends javax.swing.JFrame implements ImagemSelecionadaListener{

    
     
    private Timer timer;
    private int progresso = 0;

    public Carregar() {
        initComponents();
        iniciarTimer();

    }

     public void onImagemSelecionada(String caminhoDoArquivo) {
        exibirImagem(caminhoDoArquivo);
    }
    
    private void iniciarTimer() {
        ActionListener listener = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (progresso >= 100) {
                    timer.stop();
                    dispose(); // Fechar a janela de carregamento
                    // Abrir a tela de configuração de conexão MySQL
                    ConexaoMySQL telaConfiguracao = new ConexaoMySQL();
                    telaConfiguracao.setVisible(true);
                } else {
                    progresso += 2; // Aumente a velocidade de progresso aqui
                    jProgressBar1.setValue(progresso);
                    jLabel1.setText(progresso + "%");
                }
            }
        };

        // Atualiza a barra de progresso a cada 100 milissegundos (ou seja, 0,1 segundo)
        timer = new Timer(100, listener);
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BEM VINDO AO VALLE COCKTEIS");
        setFocusable(false);
        setFocusableWindowState(false);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 1)); // NOI18N
        jLabel1.setText("0%");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(220, 240, 2, 2);

        jProgressBar1.setBackground(new java.awt.Color(0, 0, 0));
        jProgressBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.gray, java.awt.Color.black, java.awt.Color.darkGray));
        jProgressBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        jProgressBar1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jProgressBar1.setFocusable(false);
        jProgressBar1.setStringPainted(true);
        jPanel1.add(jProgressBar1);
        jProgressBar1.setBounds(0, 363, 500, 21);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Logo Bares Gastrobar Drinkeria Elegante Preto (1).gif"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 510, 400);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 540, 400);

        setBounds(0, 0, 519, 434);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Configuração do Look and Feel Nimbus e criação da tela de carregamento */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Carregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Carregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Carregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Carregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Carregar carregar = new Carregar();
                
                carregar.setVisible(true);
                carregar.setLocationRelativeTo(null); // Centraliza a janela na tela

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables

    private void exibirImagem(String caminhoDoArquivo) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
